# Generated by Django 3.1.2 on 2021-02-08 23:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='my_field2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'IT and Software'), (2, 'Design'), (3, 'Personal Development'), (4, 'Marketing'), (5, 'Music'), (6, 'Cloud')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[(1, 'IT and Software'), (2, 'Design'), (3, 'Personal Development'), (4, 'Marketing'), (5, 'Music'), (6, 'Cloud')], max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.CharField(choices=[('P', 'Best-seller'), ('S', 'secondary'), ('D', 'danger')], max_length=1),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
