# Generated by Django 3.1.2 on 2021-02-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210211_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('S', 'Private'), ('P', 'Public'), ('I', 'In_progress')], max_length=1),
        ),
        migrations.CreateModel(
            name='CourseMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_aim', models.TextField()),
                ('course_requirements', models.TextField()),
                ('audience', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
