# Generated by Django 3.1.2 on 2021-02-09 00:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_post_my_field2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='my_field2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'IT and Software'), (2, 'Design'), (3, 'Personal Development'), (4, 'Marketing'), (5, 'Music'), (6, 'Cloud')], default=1, max_length=11),
            preserve_default=False,
        ),
    ]
